name: Run Postman API Tests

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Authenticate Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run Postman Collection
        run: postman collection run 31805593-3a667fee-7dd2-4b1b-8240-84cc9352d39c --integration-id ${{ github.run_id }}
